### ISSUE TITLE
設定に書かれたプロジェクト名のプロジェクトがない場合の動作確認

### ISSUE THREAD

**Issue by technote-space** [technote-space/auto-card-labeler#144]
```
column in config[project]
```
のように列名はチェックしているがプロジェクト名はチェックしていなかったような。。。

related #143

**Comment by technote-space** [comment]
テストケース追加

やはりチェックしていなかった。。。

```
    TypeError: Cannot use 'in' operator to search for 'column1' in undefined



      at getLabels (src/utils/label.ts:364:17)
      at Object.<anonymous>.exports.getAddLabels (src/utils/label.ts:397:30)
      at Object.<anonymous> (__tests__/utils/label.test.ts:59:10)
```

試しに存在しないプロジェクト名を指定したら #143 と同じエラーを再現
#143 で修正
